"""job_documents confirm upload fields

Revision ID: 6b9de2f768ae
Revises: efb5653f9828
Create Date: 2025-12-15 21:21:04.384627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b9de2f768ae'
down_revision: Union[str, Sequence[str], None] = 'efb5653f9828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_documents', sa.Column('status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('job_documents', sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_documents', 'uploaded_at')
    op.drop_column('job_documents', 'status')
    # ### end Alembic commands ###
