"""add last_activity_at to job_applications

Revision ID: a970cfbca94d
Revises: 04d95ed9a0ae
Create Date: 2025-12-15 17:06:05.435854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a970cfbca94d'
down_revision: Union[str, Sequence[str], None] = '04d95ed9a0ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_applications', 'last_activity_at')
    # ### end Alembic commands ###
