"""add job documents

Revision ID: ddf3fa46b993
Revises: a970cfbca94d
Create Date: 2025-12-15 19:16:10.895987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddf3fa46b993'
down_revision: Union[str, Sequence[str], None] = 'a970cfbca94d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['job_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_documents_application_id'), 'job_documents', ['application_id'], unique=False)
    op.create_index(op.f('ix_job_documents_id'), 'job_documents', ['id'], unique=False)
    op.create_index(op.f('ix_job_documents_s3_key'), 'job_documents', ['s3_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_documents_s3_key'), table_name='job_documents')
    op.drop_index(op.f('ix_job_documents_id'), table_name='job_documents')
    op.drop_index(op.f('ix_job_documents_application_id'), table_name='job_documents')
    op.drop_table('job_documents')
    # ### end Alembic commands ###
