"""add doc_type to job_documents

Revision ID: efb5653f9828
Revises: ddf3fa46b993
Create Date: 2025-12-15 19:52:54.827284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efb5653f9828'
down_revision: Union[str, Sequence[str], None] = 'ddf3fa46b993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_documents', sa.Column('doc_type', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_job_documents_doc_type'), 'job_documents', ['doc_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_documents_doc_type'), table_name='job_documents')
    op.drop_column('job_documents', 'doc_type')
    # ### end Alembic commands ###
